using System.Text.Json;
using Microsoft.AspNetCore.Routing;
using Microsoft.Data.Sqlite;

static class AdvancedFeatures
{
    private static readonly object Gate = new();
    private static string _dataRoot = "";
    private static string _connectionString = "";
    private static Timer? _timer;
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };
    private static readonly int[] AllowedIntervals = [1, 5, 15, 30, 60, 120, 240, 360, 480, 600, 720, 840, 960, 1080, 1200, 1320, 1440];
    public static void MapApi(RouteGroupBuilder api, string dataRoot, string connectionString)
    {
        _dataRoot=dataRoot; _connectionString=connectionString; EnsureSingleFile(); EnsureMenuCodeTable(); EnsureMenuCodes(); Schedule();
        api.MapGet("/order-entry-settings",()=>{var s=LoadSettings();return Results.Ok(new{menuIdSearchEnabled=s.MenuIdSearchEnabled,menuIds=ReadMenuIds()});});
        api.MapGet("/settings",()=>{var s=LoadSettings();return Results.Ok(new{s.AutoBackupEnabled,s.AutoBackupIntervalMinutes,s.AutoBackupFolder,s.MenuIdSearchEnabled,menuIds=ReadMenuIds(),latestBackup=LatestBackup(s.AutoBackupFolder)});}).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapPut("/settings",(PosSettingsRequest r)=>{if(!AllowedIntervals.Contains(r.AutoBackupIntervalMinutes))return Results.BadRequest(new{message="Ye backup interval allowed nahi hai."});var folder=string.IsNullOrWhiteSpace(r.AutoBackupFolder)?Path.Combine(_dataRoot,"Backups"):Environment.ExpandEnvironmentVariables(r.AutoBackupFolder.Trim());try{folder=Path.GetFullPath(folder);Directory.CreateDirectory(folder);var probe=Path.Combine(folder,$".mnahels-write-test-{Guid.NewGuid():N}");File.WriteAllText(probe,"ok");File.Delete(probe);}catch(Exception ex){return Results.BadRequest(new{message=$"Backup folder use nahi ho saka: {ex.Message}"});}var s=new PosSettings(r.AutoBackupEnabled,r.AutoBackupIntervalMinutes,folder,r.MenuIdSearchEnabled);SaveSettings(s);Schedule();return Results.Ok(s);}).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapPost("/backup/run",()=>{try{var path=CreateBackup(LoadSettings());return Results.Ok(new{name=Path.GetFileName(path),path,createdAt=DateTimeOffset.Now});}catch(Exception ex){return Results.BadRequest(new{message=$"Backup failed: {ex.Message}"});}}).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapGet("/backups",()=>Results.Ok(ListBackups(LoadSettings()))).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapPost("/backup/restore",(RestoreRequest r)=>{try{return Results.Ok(new{message=RestoreBackup(r.Name)});}catch(Exception ex){return Results.BadRequest(new{message=ex.Message});}}).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapGet("/users",()=>Results.Ok(ListUsers())).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapPut("/users/{id:int}/password",(int id,PasswordResetRequest r)=>{var pw=(r.Password??"").Trim();if(pw.Length<4)return Results.BadRequest(new{message="Password kam az kam 4 characters ka hona chahiye."});using var db=new SqliteConnection(_connectionString);db.Open();using var cmd=db.CreateCommand();cmd.CommandText="UPDATE Users SET PasswordHash=$hash WHERE Id=$id";cmd.Parameters.AddWithValue("$hash",PasswordHash.Create(pw));cmd.Parameters.AddWithValue("$id",id);var rows=cmd.ExecuteNonQuery();return rows==0?Results.NotFound(new{message="User mila nahi."}):Results.Ok(new{message="Password update ho gaya."});}).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapPut("/menu-ids/{productId:int}",(int productId,MenuIdRequest r)=>{var code=NormalizeCode(r.Code);if(string.IsNullOrWhiteSpace(code))return Results.BadRequest(new{message="Menu ID required."});try{using var db=new SqliteConnection(_connectionString);db.Open();using var exists=db.CreateCommand();exists.CommandText="SELECT COUNT(*) FROM Products WHERE Id=$id";exists.Parameters.AddWithValue("$id",productId);if(Convert.ToInt32(exists.ExecuteScalar())==0)return Results.NotFound(new{message="Product not found."});using var cmd=db.CreateCommand();cmd.CommandText="INSERT INTO MenuSearchCodes(ProductId,Code) VALUES($id,$code) ON CONFLICT(ProductId) DO UPDATE SET Code=excluded.Code";cmd.Parameters.AddWithValue("$id",productId);cmd.Parameters.AddWithValue("$code",code);cmd.ExecuteNonQuery();return Results.Ok(new{productId,code});}catch(SqliteException ex)when(ex.SqliteErrorCode==19){return Results.BadRequest(new{message="Ye Menu ID pehle se kisi aur item ko di hui hai."});}}).RequireAuthorization(p=>p.RequireRole("Admin"));
        api.MapPost("/menu-ids/regenerate",()=>{EnsureMenuCodes(true);return Results.Ok(new{menuIds=ReadMenuIds()});}).RequireAuthorization(p=>p.RequireRole("Admin"));
    }
    private static string SettingsPath=>Path.Combine(_dataRoot,"settings.json");
    private static string MainDbPath(){try{return new SqliteConnectionStringBuilder(_connectionString).DataSource;}catch{return Path.Combine(_dataRoot,"mnahels-pos.db");}}
    private static void EnsureSingleFile(){try{using(var db=new SqliteConnection(_connectionString)){db.Open();using var cmd=db.CreateCommand();cmd.CommandText="PRAGMA wal_checkpoint(TRUNCATE); PRAGMA journal_mode=DELETE;";cmd.ExecuteNonQuery();}SqliteConnection.ClearAllPools();var main=MainDbPath();foreach(var extra in new[]{main+"-wal",main+"-shm",main+"-journal"})try{if(File.Exists(extra))File.Delete(extra);}catch{}}catch{}}
    private static PosSettings DefaultSettings()=>new(false,1440,Path.Combine(_dataRoot,"Backups"),true);
    private static PosSettings LoadSettings(){lock(Gate){try{if(File.Exists(SettingsPath))return JsonSerializer.Deserialize<PosSettings>(File.ReadAllText(SettingsPath),JsonOptions)??DefaultSettings();}catch{}return DefaultSettings();}}
    private static void SaveSettings(PosSettings s){lock(Gate){Directory.CreateDirectory(_dataRoot);var temp=SettingsPath+".tmp";File.WriteAllText(temp,JsonSerializer.Serialize(s,JsonOptions));File.Move(temp,SettingsPath,true);}}
    private static void Schedule(){var s=LoadSettings();_timer?.Dispose();_timer=null;if(!s.AutoBackupEnabled)return;var interval=TimeSpan.FromMinutes(s.AutoBackupIntervalMinutes);_timer=new Timer(_=>{try{CreateBackup(LoadSettings());}catch{}},null,interval,interval);}
    private static string CreateBackup(PosSettings s){lock(Gate){Directory.CreateDirectory(s.AutoBackupFolder);var path=Path.Combine(s.AutoBackupFolder,$"mnahels-pos-auto-{DateTime.Now:yyyyMMdd-HHmmss}.db");using var source=new SqliteConnection(_connectionString);using var target=new SqliteConnection($"Data Source={path}");source.Open();target.Open();using(var checkpoint=source.CreateCommand()){checkpoint.CommandText="PRAGMA wal_checkpoint(FULL);";checkpoint.ExecuteNonQuery();}source.BackupDatabase(target);foreach(var old in new DirectoryInfo(s.AutoBackupFolder).GetFiles("mnahels-pos-auto-*.db").OrderByDescending(x=>x.LastWriteTimeUtc).Skip(60))try{old.Delete();}catch{}return path;}}
    private static object? LatestBackup(string folder){try{var f=new DirectoryInfo(folder).GetFiles("*.db").OrderByDescending(x=>x.LastWriteTimeUtc).FirstOrDefault();return f is null?null:new{f.Name,f.FullName,f.Length,f.LastWriteTime};}catch{return null;}}
    private static List<object> ListBackups(PosSettings s){var list=new List<object>();var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var dir in new[]{s.AutoBackupFolder,Path.Combine(_dataRoot,"Backups")}){try{foreach(var f in new DirectoryInfo(dir).GetFiles("*.db").OrderByDescending(x=>x.LastWriteTimeUtc)){if(!seen.Add(f.FullName))continue;list.Add(new{name=f.Name,path=f.FullName,sizeKb=Math.Round(f.Length/1024d),createdAt=f.LastWriteTime,folder=dir});}}catch{}}return list.Take(60).ToList();}
    private static string RestoreBackup(string? name){var requested=(name??"").Trim();if(string.IsNullOrWhiteSpace(requested))throw new Exception("Backup select karein.");var s=LoadSettings();var candidates=new[]{Path.Combine(s.AutoBackupFolder,Path.GetFileName(requested)),Path.Combine(_dataRoot,"Backups",Path.GetFileName(requested)),requested};var source=candidates.FirstOrDefault(File.Exists);if(source is null)throw new Exception("Backup file mili nahi.");lock(Gate){var safetyFolder=Path.Combine(_dataRoot,"Backups");Directory.CreateDirectory(safetyFolder);var safety=Path.Combine(safetyFolder,$"before-restore-{DateTime.Now:yyyyMMdd-HHmmss}.db");using(var current=new SqliteConnection(_connectionString))using(var backup=new SqliteConnection($"Data Source={safety}")){current.Open();backup.Open();current.BackupDatabase(backup);}using(var src=new SqliteConnection($"Data Source={source};Mode=ReadOnly"))using(var dest=new SqliteConnection(_connectionString)){src.Open();dest.Open();src.BackupDatabase(dest);}}EnsureSingleFile();return $"Restore mukammal: {Path.GetFileName(source)}. App refresh ho raha hai.";}
    private static List<object> ListUsers(){using var db=new SqliteConnection(_connectionString);db.Open();using var cmd=db.CreateCommand();cmd.CommandText="SELECT Id,Username,DisplayName,Role,IsActive FROM Users ORDER BY Role,Username";using var reader=cmd.ExecuteReader();var list=new List<object>();while(reader.Read())list.Add(new{id=reader.GetInt32(0),username=reader.GetString(1),displayName=reader.GetString(2),role=reader.GetString(3),isActive=reader.GetInt32(4)!=0});return list;}
    private static void EnsureMenuCodeTable(){using var db=new SqliteConnection(_connectionString);db.Open();using var cmd=db.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS MenuSearchCodes (ProductId INTEGER NOT NULL PRIMARY KEY, Code TEXT NOT NULL UNIQUE COLLATE NOCASE, FOREIGN KEY(ProductId) REFERENCES Products(Id) ON DELETE CASCADE);";cmd.ExecuteNonQuery();}
    private static void EnsureMenuCodes(bool regenerate=false){lock(Gate){using var db=new SqliteConnection(_connectionString);db.Open();if(regenerate){using var clear=db.CreateCommand();clear.CommandText="DELETE FROM MenuSearchCodes";clear.ExecuteNonQuery();}using var query=db.CreateCommand();query.CommandText="SELECT p.Id,c.Name FROM Products p JOIN Categories c ON c.Id=p.CategoryId ORDER BY c.SortOrder,p.Name";using var reader=query.ExecuteReader();var rows=new List<(int Id,string Category)>();while(reader.Read())rows.Add((reader.GetInt32(0),reader.GetString(1)));reader.Close();var counters=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);foreach(var row in rows){using var found=db.CreateCommand();found.CommandText="SELECT Code FROM MenuSearchCodes WHERE ProductId=$id";found.Parameters.AddWithValue("$id",row.Id);if(found.ExecuteScalar() is not null)continue;var prefix=Prefix(row.Category);counters[prefix]=counters.GetValueOrDefault(prefix)+1;var code=$"{prefix}{counters[prefix]}";while(CodeExists(db,code)){counters[prefix]++;code=$"{prefix}{counters[prefix]}";}using var add=db.CreateCommand();add.CommandText="INSERT INTO MenuSearchCodes(ProductId,Code) VALUES($id,$code)";add.Parameters.AddWithValue("$id",row.Id);add.Parameters.AddWithValue("$code",code);add.ExecuteNonQuery();}}}
    private static bool CodeExists(SqliteConnection db,string code){using var cmd=db.CreateCommand();cmd.CommandText="SELECT COUNT(*) FROM MenuSearchCodes WHERE Code=$code";cmd.Parameters.AddWithValue("$code",code);return Convert.ToInt32(cmd.ExecuteScalar())>0;}
    private static Dictionary<int,string> ReadMenuIds(){EnsureMenuCodes();using var db=new SqliteConnection(_connectionString);db.Open();using var cmd=db.CreateCommand();cmd.CommandText="SELECT ProductId,Code FROM MenuSearchCodes ORDER BY Code";using var reader=cmd.ExecuteReader();var result=new Dictionary<int,string>();while(reader.Read())result[reader.GetInt32(0)]=reader.GetString(1);return result;}
    private static string Prefix(string category){var c=category.ToLowerInvariant();if(c.Contains("burger"))return"B";if(c.Contains("wrap"))return"W";if(c.Contains("pizza"))return"P";if(c.Contains("pasta"))return"PA";if(c.Contains("broast"))return"BR";if(c.Contains("fries"))return"F";if(c.Contains("sandwich"))return"S";if(c.Contains("wing")||c.Contains("nugget"))return"N";if(c.Contains("drink")||c.Contains("shake"))return"D";if(c.Contains("dessert"))return"DS";if(c.Contains("salad"))return"SL";if(c.Contains("deal"))return"DL";if(c.Contains("extra"))return"E";var letters=new string(category.Where(char.IsLetter).Take(2).ToArray()).ToUpperInvariant();return string.IsNullOrWhiteSpace(letters)?"M":letters;}
    private static string NormalizeCode(string? value){var code=new string((value??"").Where(char.IsLetterOrDigit).ToArray()).ToUpperInvariant();return code.Length>8?code[..8]:code;}
}
record PosSettings(bool AutoBackupEnabled,int AutoBackupIntervalMinutes,string AutoBackupFolder,bool MenuIdSearchEnabled);
record PosSettingsRequest(bool AutoBackupEnabled,int AutoBackupIntervalMinutes,string? AutoBackupFolder,bool MenuIdSearchEnabled);
record MenuIdRequest(string? Code);
record RestoreRequest(string? Name);
record PasswordResetRequest(string? Password);
