/* One-time migration; removed after verified commit, never used by release builds. */
const fs=require('fs'),postcss=require('postcss');const web='src/MnahelsCafe.Pos/wwwroot',server='src/MnahelsCafe.Pos/';
const read=p=>fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n'),write=(p,s)=>fs.writeFileSync(p,s);
function edit(p,a,b){const s=read(p);if(s.split(a).length!==2)throw Error('Unique anchor: '+p+' '+a.slice(0,80));write(p,s.replace(a,b))}
function between(p,a,b,r){let s=read(p),i=s.indexOf(a),j=s.indexOf(b,i+a.length);if(i<0||j<0)throw Error('Missing range '+p);write(p,s.slice(0,i)+r+s.slice(j))}
fs.cpSync(web,process.env.RUNNER_TEMP+'/cafe-baseline',{recursive:true});
edit(server+'Program.cs','var dataRoot=OperatingSystem.IsWindows()?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"MnahelsCafePOS"):Path.Combine(builder.Environment.ContentRootPath,"App_Data");','var dataRoot=Environment.GetEnvironmentVariable("MNAHELS_DATA_ROOT")??(OperatingSystem.IsWindows()?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"MnahelsCafePOS"):Path.Combine(builder.Environment.ContentRootPath,"App_Data"));');
edit(server+'Program.cs','SeedData.Apply(db);SuperDealsMigration.Apply(db);CredentialMigrationV44.Apply(db);V42MenuMigration.Apply(db);','MenuCatalog.Initialize(db);CredentialMigrationV44.Apply(db);');
edit(server+'Program.cs','var api=app.MapGroup("/api").RequireAuthorization();','var api=app.MapGroup("/api").RequireAuthorization();MenuCatalog.MapApi(api);');
between(server+'Program.cs','api.MapGet("/menu",','api.MapGet("/customers/search",','api.MapGet("/menu",async(PosDb db)=>Results.Ok(await MenuCatalog.Read(db)));');
between(server+'AdminFeatures.cs','        api.MapGet("/admin/menu",','        api.MapPost("/products",','        api.MapGet("/admin/menu", async (PosDb db) => Results.Ok(await MenuCatalog.Read(db, includeArchived: true))).RequireAuthorization(p => p.RequireRole("Admin"));\n\n');
edit(server+'SuperDealsMigration.cs','using var tx=db.Database.BeginTransaction();','using var tx=db.Database.CurrentTransaction is null?db.Database.BeginTransaction():null;');write(server+'SuperDealsMigration.cs',read(server+'SuperDealsMigration.cs').replaceAll('tx.Commit();','tx?.Commit();'));
edit(server+'MaintenanceFeatures.cs','SeedData.Apply(db); // restore the photographed menu and the four default tables','MenuCatalog.Initialize(db, factoryReset: true); // same current defaults as first install');
edit(server+'MaintenanceFeatures.cs','"ShiftCashMovements", "OrderItems",','"OrderAmendments", "ShiftOrderAuditSnapshots", "ShiftCashMovements", "OrderItems",');
let maintenance=read(server+'MaintenanceFeatures.cs');const deletion='                    await db.Database.ExecuteSqlRawAsync($"DELETE FROM \\"{table}\\";");';if(!maintenance.includes(deletion))throw Error('Maintenance delete anchor');maintenance=maintenance.replace(deletion,'                {\n                    if (await db.Database.SqlQuery<int>($"SELECT COUNT(*) AS Value FROM sqlite_master WHERE type=\'table\' AND name={table}").SingleAsync() == 0) continue;\n'+deletion+'\n                }');write(server+'MaintenanceFeatures.cs',maintenance);
edit(server+'BookingGate.cs','var closing=context.Request.Method=="POST"&&path=="/api/shifts/close";','var closing=context.Request.Method=="POST"&&(path=="/api/shifts/close"||path=="/api/admin/database/wipe"||path=="/api/backup/restore");');
let seed=read(server+'SeedData.cs');if(!/var menuNeedsSync\s*=/.test(seed))throw Error('Seed guard');seed=seed.replace(/var menuNeedsSync\s*=[\s\S]*?;/,'var menuNeedsSync = !db.Categories.Any();').replace('else if(!db.Products.Any(x=>x.Name=="Green Tea")) SyncHotDrinksV41(db);','');write(server+'SeedData.cs',seed);
let v8=read(web+'/v8.js');v8=v8.replace("['admin','sales','customers','menu-admin','settings','pos','orders'].forEach(name=>{const el=nav.querySelector(`[data-screen=\"${name}\"]`);if(el)nav.appendChild(el)});",'');v8=v8.replace('setInterval(syncAdminNav,2500);',"const entered=window.enter;if(typeof entered==='function')window.enter=async function(...args){const value=await entered.apply(this,args);syncAdminNav();enhanceAdminCards();return value};document.addEventListener('cafe:catalog-updated',()=>{if(state.user?.role==='Admin'&&state.currentScreen==='menu-admin'&&!document.querySelector('#menu-drawer-backdrop.open'))loadAdminMenu()});");if(v8.includes('setInterval(syncAdminNav'))throw Error('Nav cleanup failed');write(web+'/v8.js',v8);
let v40=read(web+'/v40.js');v40=v40.replace('products!==renderProductsHooked','!renderProductsHooked').replace('cart!==renderCartHooked','!renderCartHooked').replace('current===addHooked','addHooked').replace('current===completeHooked','completeHooked').replace('current===salesHooked','salesHooked');v40=v40.replace('node.textContent=label;button.title=label','if(node.textContent!==label)node.textContent=label;if(button.title!==label)button.title=label').replace("if(title)title.textContent='Our Menu';if(kicker)kicker.textContent='FRONT COUNTER'","if(title&&title.textContent!=='Our Menu')title.textContent='Our Menu';if(kicker&&kicker.textContent!=='FRONT COUNTER')kicker.textContent='FRONT COUNTER'");v40=v40.replace('if(media){media.dataset.v40Image=src;media.style.backgroundImage=','if(media&&!media.style.backgroundImage){media.dataset.v40Image=src;media.style.backgroundImage=').replaceAll("if(img&&img.getAttribute('src')!==src)","if(img&&!img.getAttribute('src'))");
v40=v40.replace("}).observe(document.body,{childList:true,subtree:true})}","});qa('#product-grid,.cart-panel,#admin-orders,#screen-sales').forEach(root=>observer.observe(root,{childList:true,subtree:true}))}").replace("document.documentElement.dataset.v40Observed='1';new MutationObserver(","document.documentElement.dataset.v40Observed='1';const observer=new MutationObserver(");v40=v40.replace("setInterval(()=>{if(document.visibilityState==='visible'){arrangeNavigation();ensureWipeUi();hookRenderers();hookAdd();hookComplete();hookSales();decorateImages();decorateContext();cleanSales()}},5000);","document.addEventListener('click',event=>{if(event.target.closest?.('.nav-item,#login-form button'))requestAnimationFrame(()=>{arrangeNavigation();ensureWipeUi()})});document.addEventListener('cafe:catalog-updated',()=>{arrangeNavigation();ensureWipeUi()});");if(v40.includes('setInterval(')||v40.includes('.observe(document.body'))throw Error('v40 cleanup incomplete');write(web+'/v40.js',v40);
edit(web+'/v43.js','}).observe(document.body,{childList:true,subtree:true});',"}).observe(document.querySelector('#product-grid'),{childList:true,subtree:true});");
// Static styles only, exact cascade order; dynamic v4/v10/v51 retain their original timing.
let html=read(web+'/index.html');const tags=[...html.matchAll(/<link\s+rel="stylesheet"\s+href="([^"?]+)(?:\?[^\"]*)?"\s*>/g)];if(tags.length<40)throw Error('Incomplete stylesheet inventory');const paths=tags.map(x=>x[1]),root=postcss.parse(paths.map(p=>'/* Source: '+p+' */\n'+read(web+p)).join('\n'));
let duplicateRules=0,duplicateDeclarations=0;const seen=new Set();for(const rule of [...root.nodes].reverse()){if(rule.type!=='rule')continue;const key=rule.selector+'\0'+rule.nodes.map(n=>n.type==='decl'?[n.prop,n.value,!!n.important].join('\0'):n.toString()).join('\u0001');if(seen.has(key)){rule.remove();duplicateRules++;continue}seen.add(key)}root.walkRules(rule=>{const declarations=new Set();for(const node of [...rule.nodes].reverse()){if(node.type!=='decl')continue;const key=[node.prop,node.value,!!node.important].join('\0');if(declarations.has(key)){node.remove();duplicateDeclarations++}else declarations.add(key)}});const css=root.toString();write(web+'/cafe.css',css);
const metadata=paths.map(p=>'<meta data-cafe-style="'+p+'">').join('');let inserted=false;html=html.replace(/<link\s+rel="stylesheet"\s+href="([^"?]+)(?:\?[^\"]*)?"\s*>/g,()=>{if(inserted)return'';inserted=true;return'<link rel="stylesheet" href="/cafe.css?v=0.15.61">'+metadata});
for(const file of fs.readdirSync(web).filter(f=>f.endsWith('.js'))){let js=read(web+'/'+file);for(const p of paths)for(const op of ['=','^=','*='])js=js.replaceAll('link[href'+op+'"'+p+'"]','[data-cafe-style="'+p+'"]').replaceAll("link[href"+op+"'"+p+"']",'[data-cafe-style="'+p+'"]');new Function(js);write(web+'/'+file,js)}for(const p of paths)fs.unlinkSync(web+p);html=html.replace('</body>','<script src="/menu-sync.js?v=0.15.61"></script>\n</body>');write(web+'/index.html',html);
for(const p of [server+'MnahelsCafe.Pos.csproj','src/MnahelsCafe.Desktop/MnahelsCafe.Desktop.csproj','src/MnahelsCafe.Desktop/Program.cs','src/MnahelsCafe.Desktop/ReleaseDisplayVersion.cs','installer/MnahelsCafePOS.iss',web+'/index.html',web+'/v58.js',web+'/v66.js'])if(fs.existsSync(p))write(p,read(p).replaceAll('0.15.60','0.15.61'));
for(const file of fs.readdirSync(web).filter(f=>f.endsWith('.js')))new Function(read(web+'/'+file));const report={staticStylesheetsBefore:paths.length,staticStylesheetsAfter:1,duplicateRulesRemoved:duplicateRules,duplicateDeclarationsRemoved:duplicateDeclarations,cssBytesBefore:paths.reduce((n,p)=>n+fs.statSync(process.env.RUNNER_TEMP+'/cafe-baseline'+p).size,0),cssBytesAfter:Buffer.byteLength(css),removedPermanentPollingLoops:2};fs.mkdirSync('reports',{recursive:true});write('reports/v61-cleanup.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));fs.unlinkSync('.github/workflows/refactor-source.yml');fs.unlinkSync('scripts/refactor-source.cjs');
